api_platform:
    mapping:
        paths:
            [
                "%kernel.project_dir%/vendor/controleonline/orders/src/Entity",
                "%kernel.project_dir%/vendor/controleonline/orders/Resource",
            ]
    
