doctrine:
    orm:
        mappings:
            ControleOnline:
                is_bundle: false
                type: attribute
                dir: "%kernel.project_dir%/modules/controleonline/orders/src/Entity"
                prefix: 'ControleOnline\Entity'
                alias: ControleOnline
